### ISSUE TITLE
VeloVI applied to single-nuclei datasets

### ISSUE THREAD

**Issue by ccruizm** [YosefLab/velovi#6]
Good day! I would like to know whether the model can also be used for nuclei datasets and whether you have had any experience with that. Thanks in advance!

**Comment by WeilerP** [comment]
@ccruizm, in theory, you can apply it to single-nuclei data. I played around with it before and results from single-cell and single-nuclei data can differ. You'd have to check the usual assumptions and can use the new metrics to check if RNA velocity can/should be inferred in your case.
